language: cpp
compiler:
    - gcc
    - clang
    
before_install:
    - sudo apt-get -y install libboost-dev libboost-python-dev python-dev
    
script:
    - python waf update --files=boost
    - python waf configure
    - python waf build -v
    - ./build_directory/src/test/boost_python_exception_tests
